<?php

return [
    'type_options' => [
        'Numbers' => [
            'decimal' => 'DECIMAL',
            'double' => 'DOUBLE',
            'float' => 'FLOAT',
            'integer' => 'INTEGER',
            'mediumint' => 'MEDIUMINT',
            'bigint' => 'BIGINT',
            'smallint' => 'SMALLINT',
            'tinyint' => 'TINYINT',
        ],
        'Binary' => [
            'binary' => 'BINARY',
            'varbinary' => 'VARBINARY',
            'blob' => 'BLOB',
            'mediumblob' => 'MEDIUMBLOB',
            'longblob' => 'LONGBLOB',
            'tinyblob' => 'TINYBLOB',
            'bit' => 'BIT',
        ],
        'Strings' => [
            'char' => 'CHAR',
            'string' => 'VARCHAR',
            'text' => 'TEXT',
            'mediumtext' => 'MEDIUMTEXT',
            'longtext' => 'LONGTEXT',
            'tinytext' => 'TINYTEXT',
        ],
        'Date and Time' => [
            'date' => 'DATE',
            'datetime' => 'DATETIME',
            'time' => 'TIME',
            'timestamp' => 'TIMESTAMP',
            'year' => 'YEAR',
        ],
    ],
    'index_options' => [
        'none' => 'None',
        'primary' => 'Primary',
        'unique' => 'Unique',
        'index' => 'Index',
    ],
    'type_filament' => [
        'none' => 'None',
        'text' => 'Text Input',
        'interger' => 'Interger',
        'password' => 'Password',
        'select' => 'Select',
        'checkbox' => 'Checkbox',
        'toggle' => 'Toggle',
        'checkbox_list' => 'Checkbox List',
        'radio' => 'Radio',
        'date' => 'Date Picker',
        'datetime' => 'Datetime Picker',
        'time' => 'Time Picker',
        'file' => 'File Upload',
        'rich_text' => 'Rich Text',
        'markerdown_editor' => 'Markdown Editor',
        'repater' => 'Table Repeater',
        'builder' => 'Builder',
        'tags_input' => 'Tags Input',
        'textarea' => 'Textarea',
        'key_value' => 'Key Value',
        'color_picker' => 'Color Picker',
        'toggle_button' => 'Toggle Button',
        'hidden' => 'Hidden',
    ]
];